---
version: '3'

services:
  finrem-document-generator-client:
    image: hmcts/finrem-document-generator-client:latest
    container_name: finrem-document-generator-client
    environment:
      PDF_SERVICE_ACCESS_KEY: "${PDF_SERVICE_ACCESS_KEY}"
      EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL: http://evidence-management-client-api:4006
    ports:
      - 4009:4009
    depends_on:
      - finrem-evidence-management-client-api

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      TESTING_SUPPORT_ENABLED: "true"
      MICROSERVICEKEYS_EM_GW: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_FINREM_DOCUMENT_GENERATOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_DIVORCE: "AAAAAAAAAAAAAAAA"

  document-management-store:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:latest
    command: --wait-for-database 30
    ports:
     - 3405:8080
     - 5005:5005
    expose:
     - 5005
    environment:
      SERVER_PORT: 8080
      IDAM_SUPERUSER_EMAIL:
      IDAM_SECRET_KEY: AAAAAAAAAAAAAAAA
      GOV_NOTIFY_API_KEY:
      SPRING_DATASOURCE_URL: jdbc:postgresql://document-management-store-database:5432/evidence
      SPRING_DATASOURCE_USERNAME: evidence
      SPRING_DATASOURCE_PASSWORD: evidence
      SPRING_PROFILES_ACTIVE: dev
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
      IDAM_USER_BASE_URI: http://idam-api:8080
      IDAM_S2S_BASE_URI: http://service-auth-provider-api:8080
      S2S_NAMES_WHITELIST: sscs,divorce,ccd,em_gw,document-management-store,ccd_gw,idam-api,finrem_document_generator
      http_proxy:
      https_proxy:
      no_proxy:
      #      logging env vars
      ROOT_APPENDER: JSON_CONSOLE
      JSON_CONSOLE_PRETTY_PRINT: "false"
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: document-management-store
      REFORM_TEAM: cc
      REFORM_ENVIRONMENT: docker
      #      healthcheck env vars
      PACKAGES_ENVIRONMENT: docker
      PACKAGES_PROJECT: evidence
      PACKAGES_NAME: document-management-store
      PACKAGES_VERSION: unknown
    #      debug mode
    #    JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api
    depends_on:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api
     - azure-storage-emulator-azurite

  document-management-store-database:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-database:latest
    volumes:
     - document-management-store-database:/var/lib/postgresql/data

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: cmc-int-test@cmc.reform.hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://idam-database:5432/idam
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: cmc_it_test_secret_key
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY: OOOOOOOOOOOOOOOO
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_ADMIN: IIIIIIIIIIIIIIII
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_DIVORCE: dummy-secret
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: fake
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      REFORM_ENVIRONMENT: test
      http_proxy:
      https_proxy:
      no_proxy:
    ports:
      - 4501:8080
    expose:
      - 4501
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    ports:
     - 5430:5432
    volumes:
     - idam-database:/var/lib/postgresql/data

  finrem-evidence-management-client-api:
    image: hmcts/finrem-evidence-management-client-api:latest
    container_name: evidence-management-client-api
    environment:
      - AUTH_PROVIDER_SERVICE_CLIENT_BASEURL=http://service-auth-provider-api:8080
      - DOCUMENT_MANAGEMENT_STORE_URL=http://document-management-store:8080
      - IDAM_API_URL=http://idam-api:8080
      - AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE=finrem_document_generator
    ports:
      - 4006:4006
    depends_on:
      - service-auth-provider-api
      - document-management-store
      - idam-api

  smtp-server:
    image: mailhog/mailhog

volumes:
  idam-database:
  document-management-store-database:
  ccd-docker-azure-blob-data:
