java:
  aadIdentityName: finrem
  ingressHost: "finrem-dgcs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  applicationPort: '4009'
  image: 'https://hmcts.azurecr.io/hmcts/finrem-document-generator-client:latest'
  keyVaults:
      finrem:
          secrets:
              - finrem-doc-s2s-auth-secret
              - idam-secret
              - docmosis-api-key
              - docmosis-endpoint
