java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL: http://finrem-emca-aat.service.core-compute-aat.internal
    REFORM_ENVIRONMENT: aat
    PDF_SERVICE_BASEURL: ${PDF_SERVICE_BASEURL}rs/render
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASEURL}rs/status
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
