java:
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    environment:
        REFORM_ENVIRONMENT: aat
        EVIDENCE_MANAGEMENT_CLIENT_API_BASEURL: http://finrem-emca-aat.service.core-compute-aat.internal
        SEND_LETTER_SERIVCE_BASEURL : http://rpe-send-letter-service-aat.service.core-compute-aat.internal
